from typing import List

COLS_TO_DROP: List[str] = [
    "LocalIP",
    "OU",
    "SiteName",
    "Count",
    "Unknown",
    "Unknown",
    "GroupNames",
    "Tags",
    "HostID",
    "Platform",
    "ExPRT Critical",
    "ExPRT High",
    "ExPRT Medium",
    "ExPRT Low",
    "ExPRT Unknown",
    "Asset Criticality",
    "Asset Roles",
    "Internet exposure",
    "Managed By",
    "Data Providers",
    "Third-party Asset IDs",
    "CID",
    "Customer",
    "Recommendation Type",
    "Patch Publication Date",
    "Instance state",
]
